name: lscms
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: ValdezEdison/CMS-LS
    build_command: pip install -r requirements.txt && python manage.py collectstatic --noinput
    run_command: gunicorn --worker-tmp-dir /dev/shm lscms.wsgi:application
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: lscms.settings.production
      - key: DJANGO_SECRET_KEY
        value: django-insecure-66h&h$^hs36zz0*vg8vhjr+6h0tye&5$p@@yrha1%_*-3pc$nb
        type: SECRET
      - key: DJANGO_ALLOWED_HOST
        value: ${APP_DOMAIN}
    routes:
      - path: /
    health_check:
      http_path: /admin/login/
