# Generated by Django 5.1.6 on 2025-02-28 08:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.fields.StreamField([('api_content', 2), ('heading', 3), ('paragraph', 4), ('image', 5), ('html', 6), ('embed', 7), ('quote', 8), ('card', 14)], block_lookup={0: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter the API endpoint URL'}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'blocks/api_content.html', 'help_text': 'Template to render the API content'}), 2: ('wagtail.blocks.StructBlock', [[('api_url', 0), ('template', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('home.models.HTMLBlock', (), {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 8: ('wagtail.blocks.BlockQuoteBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('image', 11), ('button_text', 12), ('button_link', 13)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('api_content', 2), ('heading', 3), ('paragraph', 4), ('image', 5), ('html', 6), ('embed', 7), ('featured_sections', 13)], block_lookup={0: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter the API endpoint URL'}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'blocks/api_content.html', 'help_text': 'Template to render the API content'}), 2: ('wagtail.blocks.StructBlock', [[('api_url', 0), ('template', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('home.models.HTMLBlock', (), {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('text', 9), ('image', 10), ('link', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {})}, default='No content yet!'),
            preserve_default=False,
        ),
    ]
