# Generated by Django 5.1.6 on 2025-02-13 13:01

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Advertisement', max_length=255)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Ad Block',
                'verbose_name_plural': 'Ad Blocks',
            },
        ),
        migrations.CreateModel(
            name='FooterBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Footer Block',
                'verbose_name_plural': 'Footer Blocks',
            },
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Header Block',
                'verbose_name_plural': 'Header Blocks',
            },
        ),
    ]
