# Generated by Django 5.1.6 on 2025-02-13 17:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lscms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('custom_scripts', models.TextField(blank=True)),
                ('enable_tracking', models.BooleanField(default=True)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('cookie_consent_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android')], max_length=20)),
                ('header_style', models.CharField(max_length=50)),
                ('footer_style', models.CharField(max_length=50)),
                ('sidebar_enabled', models.BooleanField(default=True)),
                ('navigation_style', models.CharField(max_length=50)),
                ('color_scheme', models.JSONField(default=dict)),
                ('custom_css', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('target_platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['web', 'ios', 'android'], size=None)),
                ('target_locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['web', 'ios', 'android'], size=None)),
                ('is_dismissible', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link_url', models.CharField(max_length=500)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('platform_visibility', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['web', 'ios', 'android'], size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lscms.menuitem')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
