# Generated by Django 5.1.6 on 2025-02-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lscms', '0004_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='analytics_tracking',
            field=models.JSONField(blank=True, default=dict, help_text='Analytics tracking configuration'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='campaign_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Campaign display and tracking settings'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='style_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Custom styling options for the campaign'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='color_scheme',
            field=models.JSONField(blank=True, default=dict, help_text='Color scheme configuration'),
        ),
    ]
