# Generated by Django 5.1.6 on 2025-02-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lscms', '0005_marketingcampaign_analytics_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='campaign_content',
            field=models.JSONField(blank=True, default=dict, help_text='Campaign content blocks and metadata'),
        ),
    ]
