# Generated by Django 5.1.6 on 2025-02-28 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('default', 'Default (Blue)'), ('green', 'Green Theme'), ('purple', 'Purple Theme'), ('red', 'Red Theme'), ('teal', 'Teal Theme'), ('custom', 'Custom Colors')], default='default', help_text='Select the color theme for the admin interface', max_length=20)),
                ('custom_primary_color', models.CharField(blank=True, help_text='Custom primary color (hex code, e.g., #FF5733)', max_length=7)),
                ('custom_secondary_color', models.CharField(blank=True, help_text='Custom secondary color (hex code, e.g., #33FF57)', max_length=7)),
                ('custom_css', models.TextField(blank=True, help_text='Additional CSS to be applied to the admin interface')),
                ('logo', models.ForeignKey(blank=True, help_text='Custom logo for the admin interface', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Admin Theme',
            },
        ),
    ]
